tunnel: k3s
credentials-file: /etc/cloudflared/creds/credentials.json
# Remember, these rules route traffic from cloudflared to a local service. 
# To route traffic from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
# E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.
ingress:
# To target service inside k8s, use this pattern: service: http://service-name.service-namespace.svc.cluster.local
- hostname: ghost.my-domain.tld
  service: http://ghost-svc.ghost.svc.cluster.local
# Catch all
- service: http_status:404
