---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1 
  template:
    spec:
      containers:
      - name: cloudflared
        image: docker.io/cloudflare/cloudflared:2024.12.2
        args:
          - tunnel
          - --metrics=0.0.0.0:3333
          - --no-autoupdate
          - --protocol
          - http2
          - --config
          - /etc/cloudflared/config/config.yml
          - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
        startupProbe:
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
          failureThreshold: 60
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: cf
      - name: config
        configMap:
          name: cf
          items:
          - key: config.yml
            path: config.yml
