apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress
labels:
  - pairs:
      app: cloudflared
    includeSelectors: true
resources:
- deployment.yml

secretGenerator:
- name: cf
  files:
  - credentials.json={uuid}.json

configMapGenerator:
- name: cf
  files:
  - config.yml
